### ISSUE TITLE
Problems with SSL CA cert

### ISSUE THREAD

**Issue by juanklopper** [plotly/Plotly.jl#13]
Using Anaconda with Julia 0.3.11 (IJulia) on Windows 10.  Plotly.plot(data...) returns: Error executing request : Problem with the SSL CA cert (path? access rights?)

**Comment by scorinaldi** [comment]
Not sure if this is the same thing, but on Windows using Plotly with Ruby, I was running into this:

'OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed'

this has to do with what's written here: 
https://gist.github.com/fnichol/867550

TO FIX this error on Windows: 
1. Download http://curl.haxx.se/ca/cacert.pem
2. Save it as %USERPROFILE%/cacert.pem ( C:\Users\__you__\cacert.pem)
3. Set persistent environment variable for current user SSL_CERT_FILE as %USERPROFILE%/cacert.pem

**Comment by juanklopper** [comment]
Plotly works so well in the Jupyter notebook using Python 3.x.  Why this difficulty using IJulia in the notebook?  I'm new to Julia.

**Comment by scorinaldi** [comment]
Hi Juan, 

The error you're seeing has pretty much nothing to do with Julia / Plotly. The issue is that the API call relies on an SSL connection, and the library your using does not know to trust the SSL certificate ( for Plotly ). To tell you're connecting code to "trust" plotly's SSL certificate, you should download the .pem for the Certificate Authority, and make the change I posted above.

Did you try the fix I posted above? Did it change anything?

**Comment by MirelIe** [comment]
Hi, 
I have the same problem with SSL certification, and was not able to solve it with the method described above. 
Path to the cacert.pem has appeared in my environment variables (tested with echo %SSL_CERT_FILE%); OS - Win7.

**Comment by malmaud** [comment]
We've switched to use the `Requests` package for HTTP communication, which comes bundled with a list of trusted certificates. Please let me know if you're still having trouble.

**Comment by krcools** [comment]
Will there be a release in the near future using `Requests`? For now the change is only visible on `master`...

**Comment by malmaud** [comment]
Yes, this week.

**Comment by krcools** [comment]
Great!
