### ISSUE TITLE
Type is not a valid key

### ISSUE THREAD

**Issue by i-apellaniz** [plotly/Plotly.jl#27]
Version info:

```
Julia Version 0.6.0-dev.1133
Commit 97ca164 (2016-10-27 03:53 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```

When I try to plot 3d

```
julia> surface(Dict(["z"=>[2 3 4 5; 1 2 4 5; 1 1 2 4]]))
```

Then comes the error that `type` is not a valid key. I think there must be a conflict with `type` which should be `"type"` a `String`.

```
LoadError: ArgumentError: type is not a valid key for type String
while loading In[18], in expression starting on line 1

 in setindex!(::Dict{String,Array{Float64,2}}, ::String, ::Symbol) at ./dict.jl:388
 in #GenericTrace#1 at /home/iapellaniz/.julia/v0.6/PlotlyJS/src/traces_layouts.jl:11 [inlined]
 in Type at /home/iapellaniz/.julia/v0.6/PlotlyJS/src/traces_layouts.jl:11 [inlined]
 in #surface#93(::Array{Any,1}, ::Function, ::Dict{String,Array{Float64,2}}) at /home/iapellaniz/.julia/v0.6/PlotlyJS/src/api.jl:24
 in surface(::Dict{String,Array{Float64,2}}) at /home/iapellaniz/.julia/v0.6/PlotlyJS/src/api.jl:24
```

**Comment by spencerlyon2** [comment]
The issue here is actually a bit more subtle than that. Internally I assume that fields of a trace will be stored in a Dict (or another associative type) where the keys all have type `Symbol`. 

In this case you passed in a Dict of type `Dict{String,Array{Float64,2}}` (see the last part of the traceback you uploaded). this means the keys have type `String`. When I try to the mapping `:type => "surface"` to the dict it complains saying I can't use a key that has type `Symbol` (e.g. `:type`) in a dict where the keys have type `String`. Ultimately I should handle this better and I will get to it soon.

Until then, however, you can construct your trace using one of the methods below:

```julia
surface(z=[2 3 4 5; 1 2 4 5; 1 1 2 4])
```

or

```julia
surface(Dict([:z=>[2 3 4 5; 1 2 4 5; 1 1 2 4]]))
```
